CREATE TABLE sqlite_sequence(name,seq)

CREATE TABLE IF NOT EXISTS "users" ("id" INTEGER PRIMARY KEY  NOT NULL ,"username" VARCHAR NOT NULL  DEFAULT (null) ,"password" VARCHAR NOT NULL )

CREATE TABLE IF NOT EXISTS "users_has_roles" ("users_id" INTEGER NOT NULL , "roles_id" INTEGER NOT NULL )

CREATE TABLE IF NOT EXISTS "users_data" ("id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE , "users_id" INTEGER NOT NULL , "name" VARCHAR NOT NULL , "surname" VARCHAR NOT NULL , "email" VARCHAR)

CREATE TABLE IF NOT EXISTS "roles" ("id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE , "name" VARCHAR NOT NULL , "description" VARCHAR)

CREATE TABLE IF NOT EXISTS "roles_has_actions" ("id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE , "roles_id" INTEGER NOT NULL , "actions_id" INTEGER NOT NULL )

CREATE TABLE IF NOT EXISTS "actions" ("id" INTEGER PRIMARY KEY  NOT NULL  UNIQUE , "name" VARCHAR NOT NULL )

CREATE TABLE IF NOT EXISTS "logs" ("id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE , "user_name" VARCHAR NOT NULL , "action_name" VARCHAR NOT NULL , "datetime" DATETIME NOT NULL )